on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: ls
      - run: pwd
      - run: ls /
      - run: ls /github
      - run: ls /github/home
      - run: ls /github/workflow
      - run: ls /home
      - run: bash ../../scripts/install-development-environment
      - run: meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
      - run: ninja -C build
      - run: meson test -C build

