on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm git sudo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: bash scripts/install-development-environment
      - run: |
          for commit in $(git rev-list ${{ github.base_ref }}..${{ github.head_ref }}); do
            meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
            ninja -C build
            meson test -C build --suite devel -v
          done

