on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - run: pacman-key --init
      - run: pacman -Syu --noconfirm git sudo
      - run: git clone https://github.com/project-repo/cagebreak
      - run: git -C cagebreak checkout feature/continuous-integration
      - run: cd cagebreak ; bash scripts/install-development-environment
      - run: cd cagebreak ; meson setup build -Dxwayland=true -Dman-pages=true --buildtype=release
      - run: cd cagebreak ; ninja -C build
      - run: cd cagebreak ; meson test -C build

