name: ci
description: "CI"

on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

runs:
  using: 'docker'
  image: 'Dockerfile'
  pre-entrypoint: '../../scripts/install-development-environment'
  entrypoint: '../../scripts/test'

