name: ci

on:
  push:
    branches: [ "feature/continuous-integration", "development" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    runs:
      using: 'docker'
      image: 'Dockerfile'
      pre-entrypoint: '../../scripts/install-development-environment'
      entrypoint: '../../scripts/test'
    steps:
      - run: meson test -C build

